version: '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: dbpassword
    volumes:
    - /storage/mysql:/var/lib/mysql
    networks:
    - core-infra

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: dbpassword
    networks:
    - core-infra
#底下為 traefik 設定稿範本，如果您未啟用 traefik 容器，以下設定將不會有任何作用。如果您想使用 traefik 請務必修改 Host() 內的網址 
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.phpmyadmin.loadbalancer.server.port: "80"
        traefik.http.services.phpmyadmin.loadbalancer.server.scheme: "http"
        traefik.http.middlewares.https_redirect.redirectscheme.scheme: "https"
        traefik.http.routers.phpmyadmin_http.entrypoints: "web"
        traefik.http.routers.phpmyadmin_http.rule: "Host(`sqladm.xxps.tp.edu.tw`)"
        traefik.http.routers.phpmyadmin_http.middlewares: "https_redirect"
        traefik.http.routers.phpmyadmin_https.entrypoints: "web-secure"
        traefik.http.routers.phpmyadmin_https.rule: "Host(`sqladm.xxps.tp.edu.tw`)"
        traefik.http.routers.phpmyadmin_https.tls: "true"
        traefik.http.routers.phpmyadmin_https.tls.certresolver: "letsencrypt"

networks:
  core-infra:
    external: true
