<?php

/**
 * @file
 * sims authentication module for Drupal.
 */

require_once 'mssql.api.php';

/**
 * Implements hook_update_projects_alter().
 */
function db2health_update_projects_alter(&$projects) {
  unset($projects['db2health']);
}

/**
 * Implements hook_menu().
 */
function db2health_menu() {
  $items = array();

  $items['admin/config/people/db2health'] = array(
    'title' => t('SIMS to Health Sync settings'),
    'description' => t('Control the various settings of the SIMS and SHMS Sync module'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('db2health_settings'),
    'access arguments' => array('administer sims authentication'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/people/db2health'] = array(
    'title' => t('Sync to Health'),
    'description' => t('Provide Sync Students Data from/to Health DB user interface.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('db2health_operate'),
    'access arguments' => array('db2health operator'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function db2health_admin_paths() {
  return array(
    'admin/config/people/db2health' => TRUE,
    'admin/people/db2health' => TRUE,
  );
}

/**
 * Implements hook_help().
 */
function db2health_help($path, $arg) {
  switch ($path) {
    case 'admin/config/people/db2health':
      $output = '<p>' . t('This module sync students data between SIMS IBM DB2 database and Students Health Management System (Microsoft SQL server).') . '</p>';
      $output .= '<p></p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function db2health_permission() {
  return array(
    'db2health operator' => array(
      'title' => t('db2health operator'),
      'description' => t('Give to the nurse of your school health center or administrator.'),
    ),
  );
}

/**
 * Implements operate UI for the module.
 */
function db2health_operate($form, &$form_state) {
  $form = array();
  if (variable_get('db2health_enable')) {
    $form['help'] = array(
      '#type' => 'item',
      '#title' => t('Information:'),
      '#markup' => t('Choise which data to synchronize, students health data sync from SHMS to SIMS, then students profile data sync from SIMS to SHMS. This opretion may be take a long time, Please be patient and wait for Synchronization to be done. Do not leave or reload this page, and do not close the browser.'),
    );
    $form['datakind'] = array(
      '#type' => 'select',
      '#title' => t('Which data to synchronize:'),
      '#default_value' => 0,
      '#options' => array(0 => t('students health data'), 1 => t('students profile data')),
    );
    $form['include_nonuse'] = array(
      '#type' => 'checkbox',
      '#title' => t('Include absentee students'),
      '#default_value' => TRUE,
      '#description' => t('It is not allowed to import absentee students health data in SIMS. but if not, these data will not keep in database for ten years. I recommend to check this box.'),
      '#states' => array(
        'visible' => array(
          ':input[name="datakind"]' => array('value' => 0),
        ),
      ),
    );
    $form['delete_nonuse'] = array(
      '#type' => 'checkbox',
      '#title' => t('Delete transfer students'),
      '#default_value' => TRUE,
      '#description' => t('Keep transfer students profile in SHMS may cause duplicate seat number, check this box will auto delete these data.'),
      '#states' => array(
        'visible' => array(
          ':input[name="datakind"]' => array('value' => 1),
        ),
      ),
    );
    $form['sync_before_delete'] = array(
      '#type' => 'checkbox',
      '#title' => t('Sync health data to SIMS before delete'),
      '#default_value' => TRUE,
      '#description' => t('Before delete transfer students, sync their health data from SHMS to SIMS and keep in IBM DB2 Database.'),
      '#states' => array(
        'visible' => array(
          ':input[name="datakind"]' => array('value' => 1),
          ':input[name="delete_nonuse"]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['log'] = array(
      '#type' => 'checkbox',
      '#title' => t('Detail processing logs'),
      '#description' => t('Show the detail processing log for debug.'),
    );
    $form['start'] = array(
      '#type' => 'button',
      '#value' => t('Start Sync'),
      '#ajax' => array('callback' => 'db2health_start'),
    );
    $form['viewport'] = array(
      '#type' => 'fieldset',
      '#title' => t('Detail Logs'),
      '#collapsible' => FALSE, 
      '#collapsed' => FALSE,
    );
    $form['viewport']['log_div'] = array(
      '#type' => 'item',
    );
  }
  else {
    $form['help'] = array(
      '#type' => 'item',
      '#title' => t('Information:'),
      '#markup' => t('Please complete <em>SIMS to Health sync</em> Module settings first!'),
    );
  }

  return $form;
}

/**
 * helper function to transform Sight Data 
 */
function db2health_sight_process($sight) {
  if ((int)$sight == -1) {
    return '<0.1';
  }
  elseif ((int)$sight < 0) {
    return '*' . $sight;
  }
  else {
    return $sight;
  }
}

/**
 * Implements db2health_start().
 */
function db2health_start($form, &$form_state) {
  global $mssql_conn;
  $detail_log = '';
  $group_reset = array();
  set_time_limit(0);
  $time_start = microtime(true);
  $sdate = get_current_seme();
  $kind = $form_state['values']['datakind'];
  $sql = "select * from BASSEM where SEYEAR=? and SESEM=?";
  $chkrs = db2_query($sql, array($sdate['year'], $sdate['seme']));
  if (!db2_fetch_row($chkrs)) {
    $kind = '2';
    $detail_log .= '<p>' . t('The SIMS database has not upgrade to new semester.') . '</p>';
  }
  db2_free_result($chkrs);
  $sql = "select * from [Health].[dbo].[Sem] where [SchYears]='" . $sdate['year'] . "' and [Sem]='" . $sdate['seme'] . "'";
  $chkrs = mssql_operate($sql);
  if (!mssql_fetch_row($chkrs)) {
    $kind = '3';
    $detail_log .= '<p>' . t('The SHMS database has not upgrade to new semester.') . '</p>';
  }
  mssql_free_result($chkrs);
  $hpa = array("a31" => "臺北市", "a01" => "新北市", "a02" => "宜蘭縣", "a03" => "桃園市", "a04" => "新竹縣", "a05" => "苗栗縣",
               "a06" => "臺中市", "a07" => "彰化縣", "a08" => "南投縣", "a09" => "雲林縣", "a10" => "嘉義縣", "a11" => "臺南市",
               "a12" => "高雄市", "a13" => "屏東縣", "a14" => "臺東縣", "a15" => "花蓮縣", "a16" => "澎湖縣", "a17" => "基隆市",
               "a18" => "新竹市", "a20" => "嘉義市", "a71" => "金門縣", "a72" => "連江縣");
  for ($grade=1; $grade<=6; $grade++) {
    $seyear = (int)$sdate['year'] - $grade + 1;
    if (strlen($seyear) == 2) {
      $seyear = '0' . $seyear;
    }
    if ($kind == '0') {
      $sql = "select * from STUDENT a left join STDFAM b on a.ID=b.STDID where a.YEAR=? and a.SEYEAR=? order by a.YEAR,a.CLASSNO,a.NO";
      $rs = db2_query($sql, array($grade, $seyear));
      while (db2_fetch_row($rs)) {
        $stdid = db2_result($rs, 'ID');
        $stdname = db2_result($rs, 'NAME');
        $idno = db2_result($rs, 'IDNO');
        $classno = db2_result($rs, 'CLASSNO');
        $myclass = $grade.$classno;
        $seat = db2_result($rs, 'NO');
        if (db2_result($rs, "STATUS") == '0') {
          $atschool = TRUE;
        }
        else {
          $atschool = FALSE;
        }
        $sql = "select * from BASCLS where SEYEAR=? and SESEM=? and CLASSID=?";
        $classrs = db2_query($sql, array($sdate['year'], $sdate['seme'], $myclass));
        if (db2_fetch_row($classrs)) {
          $class_name = db2_result($classrs, 'CLASSNAME');
        }
        if ($form_state['values']['log']) {
          $detail_log .= '<p>' . t('processing') . " $class_name ($seat) $stdname......<br />";
        }
        if (!$form_state['values']['include_nonuse'] && !$atschool) {
          if ($form_state['values']['log']) {
            $detail_log .= t('This student is absentee, skip processing.') . "<br />";
          }
        }
        else {
          $sql = "select [Weight],[Height] from [Health].[dbo].[WH] where [PID]='$idno' and [GradeID]='$grade' and [Sem]='" . $sdate['seme'] . "'";
          $hrs = mssql_operate($sql);
          if ($row = mssql_fetch_row($hrs)) {
            if (!empty($row[0]) && !empty($row[1]) && $row[0]!='0.0' && $row[1]!='0.0') {
              if ($form_state['values']['log']) {
                $detail_log .= t('Retrive <em>Weight & Height</em> data for this student.') . ":$row[0] $row[1]<br />";
              }
              $w = $row[0];
              $h = $row[1];
              $hh = $h / 100;
              $bmi = round($w/($hh*$hh)*100) / 100;
              $sql = "select * from SEMHWL where SEYEAR=? and SESEM=? and STDID=?";
              $shrs = db2_query($sql, array($sdate['year'], $sdate['seme'], $stdid));
              if (db2_fetch_row($shrs)) {
                if ($form_state['values']['log']) {
                  $detail_log .= t('Found this student`s health record in SIMS. Now update his <em>Weight & Height</em> data.') . "<br />";
                }
                $sql = "update SEMHWL set WEIGHT=?, HIGHT=?, WHVALUE=? where SEYEAR=? and SESEM=? and STDID=?";
                db2_operate($sql, array($w, $h, $bmi, $sdate['year'], $sdate['seme'], $stdid));
              }
              else {
                if ($form_state['values']['log']) {
                  $detail_log .= t('Can not found this student`s health record in SIMS. Now append new record and insert his <em>Weight & Height</em> data.') . "<br />";
                }
                $sql = "insert into SEMHWL (SEYEAR,SESEM,STDID,WEIGHT,HIGHT,WHVALUE) values(?,?,?,?,?,?)";
                db2_operate($sql, array($sdate['year'], $sdate['seme'], $stdid, $w, $h, $bmi));
              }
            }
          }
          mssql_free_result($hrs);
          $sql = "select [Sight0L],[Sight0R],[SightL],[SightR],[ENear],[EFar],[ESan],[EWeak] from [Health].[dbo].[Sight] where [PID]='$idno' and [GradeID]='$grade' and [Sem]='" . $sdate['seme'] . "'";
          $hrs = mssql_operate($sql);
          while ($row = mssql_fetch_row($hrs)) {
            if (!empty($row[1])) {
              if ($form_state['values']['log']) {
                $detail_log .= t('Retrive <em>Sight</em> data for this student.') . ": $row[0] $row[1] $row[2] $row[3]<br />";
              }
              $l0 = db2health_sight_process($row[0]);
              $r0 = db2health_sight_process($row[1]);
              $l = db2health_sight_process($row[2]);
              $r = db2health_sight_process($row[3]);
              $diag = array();
              if (trim($row[4]) == '1') {
                $diag[] = '近視';
              }
              if (trim($row[5]) == '1') {
                $diag[] = '遠視';
              }
              if (trim($row[6]) == '1') {
                $diag[] = '散光';
              }
              if (trim($row[7]) == '1') {
                $diag[] = '弱視';
              }
              $sig = implode('&', $diag);
              $sql = "select * from SEMHWL where SEYEAR=? and SESEM=? and STDID=?";
              $shrs = db2_query($sql, array($sdate['year'], $sdate['seme'], $stdid));
              if (db2_fetch_row($shrs)) {
                if ($form_state['values']['log']) {
                  $detail_log .= t('Found this student`s health record in SIMS. Now update his <em>Sight</em> data.') . "<br />";
                }
                $sql = "update SEMHWL set LSIG=?, RSIG=?, MLSIG=?, MRSIG=?, SIGDIAG=? where SEYEAR=? and SESEM=? and STDID=?";
                db2_operate($sql, array($l0, $r0, $l, $r, $sig, $sdate['year'], $sdate['seme'], $stdid));
              }
              else {
                if ($form_state['values']['log']) {
                  $detail_log .= t('Can not found this student`s health record in SIMS. Now append new record and insert his <em>Sight</em> data.') . "<br />";
                }
                $sql = "insert into SEMHWL (SEYEAR,SESEM,STDID,LSIG,RSIG,MLSIG,MRSIG,SIGDIAG) values(?,?,?,?,?,?,?,?)";
                db2_operate($sql, array($sdate['year'], $sdate['seme'], $stdid, $l0, $r0, $l, $r, $sig));
              }
            }
          }
        }
      }
    }
    elseif ($kind == '1') {
      $sql = "select * from STUDENT a left join STDFAM b on a.ID=b.STDID where a.YEAR=? and a.SEYEAR=? order by a.YEAR,a.CLASSNO,a.NO";
      $rs = db2_query($sql, array($grade, $seyear));
      while (db2_fetch_row($rs)) {
        $stdid = db2_result($rs, 'ID');
        $stdno = db2_result($rs, 'STDNO');
        $idno = db2_result($rs, 'IDNO');
        $stdname = db2_result($rs, 'NAME');
        $gender = (db2_result($rs, 'SEX')=='0') ?2 :1;
        $seyear = db2_result($rs, 'SEYEAR');
        $classno = db2_result($rs, 'CLASSNO');
        $myclass = $grade.$classno;
        $classno = (int)$classno;
        $seat = db2_result($rs, 'NO');
        $birthday = db2_result($rs, 'BIRTHDAY');
        $birthday = substr($birthday,0,4) . '/' . substr($birthday,4,2) . '/' . substr($birthday,-2);
        $blood = db2_result($rs, 'BLOOD');
        $father = db2_result($rs, 'FNAME');
        $mother = db2_result($rs, 'MNAME');
        $guardian = db2_result($rs, 'SNAME');
        if (empty($guardian)) {
          $guardian = db2_result($rs, 'S2NAME');
        }
        $tel = db2_result($rs, 'CPGSM');
        if (empty($tel)) {
          $tel = db2_result($rs, 'CPTEL');
        }
        $country = db2_result($rs, 'CPA');
        $city = db2_result($rs, 'CPB');
        $town = db2_result($rs, 'CPC');
        $neighbor = db2_result($rs, 'CPD');
        $sql="select * from DB2ADMIN.ADDR_CITY where COUNTRY=? and ID=?";
        $cityrs = db2_query($sql, array($country, $city));
        if (db2_fetch_row($cityrs)) {
          $city_name = db2_result($cityrs, 'CITY');
        }
        $sql="select * from DB2ADMIN.ADDR_TOWN where CITY=? and ID=?";
        $townrs = db2_query($sql, array($city, $town));
        if (db2_fetch_row($townrs)) {
          $town_name = db2_result($townrs, 'TOWN');
        }
        $addr = $hpa['a'.$country] . $city_name . $town_name . $neighbor . '鄰' . db2_result($rs, 'CPE');
        $zip = 100;
        $sql = "select [Zip] from [Health].[dbo].[Zip] where [Town]='" . $city_name . "'";
        $ziprs = mssql_operate($sql);
        if ($ziprs) {
          if ($row = mssql_fetch_row($ziprs)) {
            $zip = $row[0];
          }
        }
        mssql_free_result($ziprs);
        $urgent = trim(db2_result($rs, 'SGSM'));
        if (empty($urgent)) {
          $urgent = trim(db2_result($rs, 'SOTEL'));
          if (empty($urgent)) {
            $urgent = trim(db2_result($rs, 'SHTEL'));
            if (empty($urgent)) {
              $urgent = trim(db2_result($rs, 'S2GSM'));
              if (empty($urgent)) {
                $urgent = trim(db2_result($rs, 'S2OTEL'));
                if (empty($urgent)) {
                  $urgent = trim(db2_result($rs, 'S2HTEL'));
                  if (empty($urgent)) {
                    $urgent = $tel;
                  }
                }
              }
            }
          }
        }
        if (db2_result($rs, "STATUS") == '0') {
          $atschool = TRUE;
        }
        else {
          $atschool = FALSE;
        }
        $sql = "select * from BASCLS where SEYEAR=? and SESEM=? and CLASSID=?";
        $classrs = db2_query($sql, array($sdate['year'], $sdate['seme'], $myclass));
        if (db2_fetch_row($classrs)) {
          $class_name = db2_result($classrs, 'CLASSNAME');
        }
        if ($form_state['values']['log']) {
          $detail_log .= '<p>' . t('processing') . " $class_name ($seat) $stdname......<br />";
        }
        if ($form_state['values']['delete_nonuse'] && !$atschool) {
          if ($form_state['values']['log']) {
            $detail_log .= t('This student has transfer to another school.') . "<br />";
          }
          if ($form_state['values']['sync_before_delete']) {
            if ($form_state['values']['log']) {
              $detail_log .= t('Now Sync all of <em>Weight & Height</em> data to SIMS for this student.') . "<br />";
            }
            $sql = "select [GradeID],[Sem],[Weight],[Height] from [Health].[dbo].[WH] where [PID]='$idno'";
            $hrs = mssql_operate($sql);
            while ($row = mssql_fetch_row($hrs)) {
              if (!empty($row[0]) && !empty($row[1]) && !empty($row[2]) && !empty($row[3])) {
                $oldyear = $seyear + $row[0] - 1;
                $oldseme = $row[1];
                $w = $row[2];
                $h = $row[3];
                $hh = $h / 100;
                $bmi = round($w/($hh*$hh)*100) / 100;
                $sql = "select * from SEMHWL where SEYEAR=? and SESEM=? and STDID=?";
                $shrs = db2_query($sql, array($oldyear, $oldseme, $stdid));
                if (db2_fetch_row($shrs)) {
                  if ($form_state['values']['log']) {
                    $detail_log .= t('Found this student`s @year school year and @seme semester health record in SIMS. Now update his <em>Weight & Height</em> data.', array('@year' => $oldyear, '@seme' => $oldseme)) . "<br />";
                  }
                  $sql = "update SEMHWL set WEIGHT=?, HEIGHT=?, WHVALUE=? where SEYEAR=? and SESEM=? and STDID=?";
                  db2_operate($sql, array($w, $h, $bmi, $oldyear, $oldseme, $stdid));
                }
                else {
                  if ($form_state['values']['log']) {
                    $detail_log .= t('Can not found this student`s @year school year and @seme semester health record in SIMS. Now append new record and insert the <em>Weight & Height</em> history record.', array('@year' => $oldyear, '@seme' => $oldseme)) . "<br />";
                  }
                  $sql = "insert into SEMHWL (SEYEAR,SESEM,STDID,WEIGHT,HEIGHT,WHVALUE) values(?,?,?,?,?,?)";
                  db2_operate($sql, array($oldyear, $oldseme, $stdid, $w, $h, $bmi));
                }
              }
            }
            mssql_free_result($hrs);
            if ($form_state['values']['log']) {
              $detail_log .= t('Now Sync all of <em>Sight</em> data to SIMS for this student.') . "<br />";
            }
            $sql = "select [GradeID],[Sem],[Sight0L],[Sight0R],[SightL],[SightR],[ENear],[EFar],[ESan],[EWeak] from [Health].[dbo].[Sight] where [PID]='$idno'";
            $hrs = mssql_operate($sql);
            while ($row = mssql_fetch_row($hrs)) {
              if (!empty($row[0]) && !empty($row[1]) && !empty($row[3])) {
                $oldyear = $seyear + $row[0] - 1;
                $oldseme = $row[1];
                $l0 = db2health_sight_process($row[2]);
                $r0 = db2health_sight_process($row[3]);
                $l = db2health_sight_process($row[4]);
                $r = db2health_sight_process($row[5]);
                $diag = array();
                if (trim($row[6]) == '1') {
                  $diag[] = '近視';
                }
                if (trim($row[7]) == '1') {
                  $diag[] = '遠視';
                }
                if (trim($row[8]) == '1') {
                  $diag[] = '散光';
                }
                if (trim($row[9]) == '1') {
                  $diag[] = '弱視';
                }
                $sig = implode('&', $diag);
                $sql = "select * from SEMHWL where SEYEAR=? and SESEM=? and STDID=?";
                $shrs = db2_query($sql, array($oldyear, $oldseme, $stdid));
                if (db2_fetch_row($shrs)) {
                  if ($form_state['values']['log']) {
                    $detail_log .= t('Found this student`s @year school year and @seme semester health record in SIMS. Now update his <em>Sight</em> data.', array('@year' => $oldyear, '@seme' => $oldseme)) . "<br />";
                  }
                  $sql = "update SEMHWL set LSIG=?, RSIG=?, MLSIG=?, MRSIG=?, SIGDIAG=? where SEYEAR=? and SESEM=? and STDID=?";
                  db2_operate($sql, array($l0, $r0, $l, $r, $sig, $oldyear, $oldseme, $stdid));
                }
                else {
                  if ($form_state['values']['log']) {
                    $detail_log .= t('Can not found this student`s @year school year and @seme semester health record in SIMS. Now append new record and insert the <em>Sight</em> history record.', array('@year' => $oldyear, '@seme' => $oldseme)) . "<br />";
                  }
                  $sql = "insert into SEMHWL (SEYEAR,SESEM,STDID,LSIG,RSIG,MLSIG,MRSIG,SIGDIAG) values(?,?,?,?,?,?,?,?)";
                  db2_operate($sql, array($oldyear, $oldseme, $stdid, $l0, $r0, $l, $r, $sig));
                }
              }
            }
          }
          if ($form_state['values']['log']) {
            $detail_log .= t('Now delete this student from SHMS.') . "<br />";
          }
          $sql = "delete [Health].[dbo].[St] where [PID]='$idno'";
          $hrs = mssql_operate($sql);
          if (!$hrs) {
            $detail_log .= '<p>' . t('error when delete transfer student from Health database') . "......<br />";
          }
        }
        else {
          $sql = "select * from [Health].[dbo].[St] where [PID]='$idno'";
          $hrs = mssql_operate($sql);
          if (!$hrs) {
            $detail_log .= '<p>' . t('error when query Health database') . "......<br />";
          }
          else {
            if (mssql_fetch_row($hrs)) {
              if ($form_state['values']['log']) {
                $detail_log .= t('Found this student in SHMS. Now update his profile data.') . "<br />";
              }
              $sql = "update [Health].[dbo].[St] set [Guy]=N'$stdname',[SexID]='$gender',[Years]='$seyear',[ClassID]='$classno',[Seat]='$seat',[Birthday]='$birthday',[Dad]='$father',[Mom]='$mother',[Guardian]='$guardian',[Zip]='$zip',[Tel1]='$tel',[Address]='$addr',[EmergencyCall]='$urgent',[Blood]='$blood',[GuyID]='$stdno' where [PID]='$idno'";
              $ret = mssql_operate($sql);
              if (!$ret) {
                $detail_log .= '<p>' . t('error when update student profile to Health database') . "......<br />";
              }
            }
            else {
              if ($form_state['values']['log']) {
                $detail_log .= t('Can not found this student in SHMS. Now insert this student to SHMS.') . "<br />";
              }
              $sql = "insert into [Health].[dbo].[St] ([PID],[Guy],[SexID],[Years],[ClassID],[Seat],[Birthday],[Dad],[Mom],[Guardian],[Zip],[Tel1],[Address],[EmergencyCall],[Blood],[GuyID]) values('$idno',N'$stdname','$gender','$seyear','$classno','$seat','$birthday','$father','$mother','$guardian','$zip','$tel','$addr','$urgent','$blood','$stdno')";
              $ret = mssql_operate($sql);
              if (!$ret) {
                $detail_log .= '<p>' . t('error when insert student profile to Health database') . "......<br />";
              }
            }
          }
        }
      }
    }
  }
  $time_end = microtime(true);
  $time_spend = $time_end - $time_start;
  $detail_log .= '<br>' . t('It takes') . ' ' . $time_spend . ' ' . t('seconds.');
  $commands = array();
  $commands[] = ajax_command_html('#edit-log-div', $detail_log);

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Implements settings for the module.
 */
function db2health_settings() {
  $form['db2health_basic'] = array(
    '#type' => 'fieldset',
    '#title' => t('MsSQL Server'),
    '#collapsible' => TRUE,
  );
  $form['db2health_basic']['info'] = array(
    '#type' => 'item',
    '#markup' => t('This module retrive students profile data from SIMS (IBM DB2 database) and students health data from SHMS (Microsoft SQL Server), Then sync between the two system. To using this module, you need to install <strong>freetds</strong> and <strong>php-mssql</strong> on your drupal server.<br>If your server is Linux OS, you should install <em>epel repositories</em> first, then do that with <em>yum install freetds php-mssql</em>.<br> After freetds installed, Please complete the freetds configure:<br>1. find freetds.conf location with this command <em>whereis freetds.conf</em><br>2. edit the file and append contents like blow:<br>[health]<br>host=ip or dn<br>port=1433<br>3. save and restart apache.'),
  );
  $form['db2health_basic']['db2health_server'] = array(
    '#type' => 'textfield',
    '#title' => t('MsSQL Server'),
    '#default_value' => variable_get('db2health_server', ''),
    '#description' => t('Input the Microsoft SQL Server`s name, must match the freetds.conf configure, for example: health.'),
  );
  $form['db2health_basic']['db2health_server_sa'] = array(
    '#type' => 'textfield',
    '#title' => t('SA or Domain Admin Account'),
    '#default_value' => variable_get('db2health_server_sa', ''),
    '#description' => t('The server`s management account name.'),
  );
  $form['db2health_basic']['db2health_server_pass'] = array(
    '#type' => 'textfield',
    '#title' => t('Password of SA'),
    '#default_value' => variable_get('db2health_server_pass', ''),
    '#description' => t('The password of this server`s management account.'),
  );
  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save sims configuration'),
  );
  $form['#submit'] = array('db2health_server_test');
  if (!isset($form['#theme'])) {
    $form['#theme'] = 'system_settings_form';
  }

  return $form;
}

/**
 * Implements db2health_server_test().
 */
function db2health_server_test($form, &$form_state) {
  $error = '';
  form_state_values_clean($form_state);
  foreach ($form_state['values'] as $key => $value) {
    if (is_array($value) && isset($form_state['values']['array_filter'])) {
      $value = array_keys(array_filter($value));
    }
    variable_set($key, trim($value));
  }

  $mssql_host = variable_get('db2health_server');
  $sa = variable_get('db2health_server_sa');
  $pass = variable_get('db2health_server_pass');
  if (!empty($mssql_host) && !empty($sa) && !empty($pass)) {
    $ret = mssql_test();
    if (!$ret) {
      $error .= t('Connect to Microsoft SQL Server failed. Please check freetds.conf configure.');
    }
  }
  else {
    $error .= t('The database server settings not completed.');
  }

  if ($error != '') {
    drupal_set_message($error . t('The configuration options have been saved, but you should check again!'), 'error');
    variable_set('db2health_enable', FALSE);
  }
  else {
    drupal_set_message(t('The Server configure was setting perfectly. The configuration options have been saved. Thank you!'));
    variable_set('db2health_enable', TRUE);
  }
}
