<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\UserInterface;

require 'gsync.api.php';

function gsync_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'admin/config/people/gsync':
            $output = '<p>本模組提供將臺北市教育人員單一身分驗證師生帳號同步到 G Suite 網域的功能。請先向 Google 申請介接專案，完成模組設定後，才能啟用模組。</p>';

            return $output;
    }
}

function tpedu_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    $config = \Drupal::config('tpedu.settings');
    if ($config->get('enable') && ($form_id == 'user_login_block' || $form_id == 'user_login_form')) {
        unset($form['links']);
        if (!$config->get('allow_default_login')) {
            unset($form['name']);
            unset($form['pass']);
        }
        $form['submit_tpedu'] = array(
            '#type' => 'html_tag',
            '#tag' => 'img',
            '#attributes' => array(
                'src' => '//'.$_SERVER['HTTP_HOST'].'/'.drupal_get_path('module', 'tpedu').'/tpedusso.png',
                'style' => 'cursor: pointer; border:none; width:240px;',
                'title' => '使用臺北市教育人員單一身分驗證登入',
                'onclick' => 'tpedussoAuth();',
            ),
        );
        if ($config->get('google_enable')) {
            $form['submit_google'] = array(
                '#type' => 'html_tag',
                '#tag' => 'img',
                '#attributes' => array(
                    'src' => '//'.$_SERVER['HTTP_HOST'].'/'.drupal_get_path('module', 'tpedu').'/google.png',
                    'style' => 'cursor: pointer; border:none; width:240px;',
                    'title' => '使用 Google 帳號登入',
                    'onclick' => 'googleAuth();',
                ),
            );
        }
        if ($config->get('personal_data_notice')) {
            $form['extra_info'] = array(
                '#markup' => '<p>我已經閱讀貴網站<a href="/personal_data_notice">個人資料收集政策</a>，我同意貴網站取得我的個人資料！</p>',
            );
        }
        $form['#attached']['library'][] = 'tpedu/tpedusso';
        $form['#attached']['drupalSettings']['tpedu']['tpedusso'] = array(
            'clientId' => $config->get('client_id'),
            'callBack' => $config->get('call_back'),
            'googleClientId' => $config->get('google_client_id'),
            'googleApikey' => $config->get('google_apikey'),
        );
    }
}

function tpedu_user_logout($account)
{
    $redirect = \Drupal::config('tpedu.settings')->get('logout_goto_url');
    if ($redirect) {
        $response = new RedirectResponse(Url::fromRoute($redirect));
        $response->send();
    }
}

function tpedu_user_view(array &$build, UserInterface $account, EntityViewDisplayInterface $display)
{
    $config = \Drupal::config('tpedu.settings');
    drupal_set_message($account->get('init'));
    if ($config->get('enable') && $account->get('init')->getValue() == 'tpedu') {
        if ($display->getComponent('birthday')) {
            $build['birthday'] = array(
                '#type' => 'item',
                '#title' => '出生日期',
                '#markup' => \Drupal::service('date.formatter')->format($account->tpedu->birthdate),
            );
        }
        if ($display->getComponent('gender')) {
            $build['gender'] = array(
                '#type' => 'item',
                '#title' => '性別',
                '#markup' => ($account->tpedu->gender == 2) ? '女' : '男',
            );
        }
        if ($account->tpedu->student) {
            if ($display->getComponent('stdno')) {
                $build['stdno'] = array(
                    '#type' => 'item',
                    '#title' => '學號:',
                    '#markup' => $account->tpedu->id,
                );
            }
            if ($display->getComponent('classname')) {
                $build['classname'] = array(
                    '#type' => 'item',
                    '#title' => '就讀班級',
                    '#markup' => $account->tpedu->dept_name,
                );
            }
            if ($display->getComponent('seat')) {
                $build['seat'] = array(
                    '#type' => 'item',
                    '#title' => '座號',
                    '#markup' => $account->tpedu->seat,
                );
            }
        } else {
            if ($display->getComponent('depname')) {
                $build['depname'] = array(
                    '#type' => 'item',
                    '#title' => '行政部門',
                    '#markup' => $account->tpedu->dept_name,
                );
            }
            if ($display->getComponent('titlename')) {
                $build['titlename'] = array(
                    '#type' => 'item',
                    '#title' => '職稱',
                    '#markup' => $account->tpedu->role_name,
                );
            }
            if (!empty($account->tpedu->class) && $display->getComponent('class')) {
                $build['proclass'] = array(
                    '#type' => 'item',
                    '#title' => '導師班級',
                    '#markup' => $account->tpedu->class,
                );
            }
        }
        if ($display->getComponent('email')) {
            $build['email'] = array(
                '#type' => 'item',
                '#title' => '電子郵件',
                '#markup' => $account->tpedu->email,
            );
        }
    }
}
