<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

require 'gevent.api.php';

function gevent_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.gevent':
            $output = '<p>本模組將為您新增「行事曆事件」內容類型，編輯事件時會自動同步到 G Suite，並提供「學校行事曆」頁面。</p>';

            return $output;
    }
}

function gevent_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    $config = \Drupal::config('gevent.settings');
    if ($config->get('enable')) {
        $node = $form_state->getFormObject()->getEntity();
        if ($node->get('type')->value == $config->get('content_type')) {
            unset($form[$config->get('field_calendar_id')]);
            unset($form[$config->get('field_event_id')]);
        }
    }
}

function gevent_node_insert(EntityInterface $node)
{
    $config = \Drupal::config('gevent.settings');
    if ($config->get('enable') && $node->get('type')->value == $config->get('content_type')) {
        $event = gs_syncEvent($node);

        $calendar_id = $event->getOrganizer()->getEmail();
        $event_id = $event->getId();
        $node->set($config->get('field_calendar_id'), $claendar_id);
        $node->set($config->get('field_event_id'), $event_id);
        $node->save();
    }
}

function gevent_node_update(EntityInterface $node)
{
    $config = \Drupal::config('gevent.settings');
    if ($config->get('enable') && $node->get('type')->value == $config->get('content_type')) {
        $event = gs_syncEvent($node);

        $calendar_id = $event->getOrganizer()->getEmail();
        $event_id = $event->getId();
        $node->set($config->get('field_calendar_id'), $claendar_id);
        $node->set($config->get('field_event_id'), $event_id);
        $node->save();
    }
}

function gevent_node_delete(EntityInterface $node)
{
    $config = \Drupal::config('gevent.settings');
    if ($config->get('enable') && $node->get('type')->value == $config->get('content_type')) {
        $calendar_id_field = $config->get('field_calendar_id');
        if (substr($calendar_id_field, 0, 6) == 'field_') {
            $calendar_id_obj = $node->$calendar_id_field;
            if (isset($calendar_id_obj['und'][0])) {
                $calendar_id = $calendar_id_obj['und'][0]['value'];
            }
        } else {
            $calendar_id = $node->$calendar_id_field;
        }
        $event_id_field = $config->get('field_event_id');
        if (substr($event_id_field, 0, 6) == 'field_') {
            $event_id_obj = $node->$event_id_field;
            if (isset($event_id_obj['und'][0])) {
                $event_id = $event_id_obj['und'][0]['value'];
            }
        } else {
            $event_id = $node->$event_id_field;
        }
        gs_deleteEvent($calendar_id, $event_id);
    }
}
