<?php

/**
 * @file
 * the install file for the simsauth module
 */

/**
 * Implements hook_uninstall().
 */
function gevent_uninstall() {
  variable_del('gevent_node_type');
  variable_del('gevent_domain');
  variable_del('gevent_admin');
}

/**
 * Implements hook_enable().
 */
function gevent_enable() {
  variable_set('gevent_enable', FALSE);
}

/**
 * Implements hook_disable().
 */
function gevent_disable() {
  variable_set('gevent_enable', FALSE);
}
