<?php

use Drupal\Core\Routing\RouteMatchInterface;

function tpedunews_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.tpedunews':
            $output = '<p>本模組將為您新增教育局最新消息新聞聯播，並提供「教育局最新消息」區塊，您也可以使用 aggregator 模組提供的「FEED聯播」區塊。</p>';

            return $output;
    }
}

function tpedunews_theme()
{
    return [
        'tpedunews_block' => [
            'variables' => [
                'items' => array(),
            ],
        ],
    ];
}
